### ISSUE TITLE
Allow running workflow generation script from any directory

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#129]
Use cases:

1. From IntelliJ, when I click the "play" button next to Kotlin shebang in main.kts file, it calls the script using the absolute path and the result is like this:

```
$ /home/piotr/repos/priv/github-actions-kotlin-dsl/.github/workflows/_GenerateWorkflows.main.kts
java.io.FileNotFoundException: .github/workflows/build.yaml (No such file or directory)
    at java.base/java.io.FileOutputStream.open0(Native Method)
    at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
    at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
    at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
    at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
    at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
    at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
    at it.krzeminski.githubactions.yaml.ToYamlKt.writeToFile(ToYaml.kt:21)
    at it.krzeminski.githubactions.yaml.ToYamlKt.writeToFile$default(ToYaml.kt:16)
    at _GenerateWorkflows_main.<init>(_GenerateWorkflows.main.kts:17)
```

2. In the console, just being in .github/workflows. The result is similar to the above one.

Related: https://kotlinlang.slack.com/archives/C02UUATR7RC/p1646349183678099

FYI @NikkyAI

**Comment by krzema12** [comment]
To make it work from any directory, just set `sourceFile` to `__FILE__.toPath()`.
