### ISSUE TITLE
[Bug] Wrappers update check job cannot find date.txt

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-kotlin-dsl#379]
See https://github.com/krzema12/github-actions-kotlin-dsl/runs/7624054781?check_suite_focus=true#step:4:143

```
 Error: Exception in thread "main" java.io.FileNotFoundException: build/action-yaml/date.txt (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
	at it.krzeminski.githubactions.wrappergenerator.metadata.MetadataReadingKt.deleteActionYamlCacheIfObsolete(MetadataReading.kt:92)
	at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.generateWrappers(GenerationEntryPoint.kt:40)
	at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.main(GenerationEntryPoint.kt:35)
	at it.krzeminski.githubactions.wrappergenerator.GenerationEntryPointKt.main(GenerationEntryPoint.kt)
```

https://github.com/krzema12/github-actions-kotlin-dsl/blob/b373cf73760fa62bfd334864ffe79b3d0300c456/wrapper-generator/src/main/kotlin/it/krzeminski/githubactions/wrappergenerator/metadata/MetadataReading.kt#L92

**Comment by krzema12** [comment]
@jmfayard would you be able to help here please?

**Comment by krzema12** [comment]
Seems to be related to switching to Zulu JDK: https://github.com/krzema12/github-actions-kotlin-dsl/commit/b373cf73760fa62bfd334864ffe79b3d0300c456

**Comment by jmfayard** [comment]
Usually problem with files like this one are due to whether the current directory is `github-actions-kotlin-dsl` or the Gradle module like `wrappergenerator`. Very frequent boring problem.

**Comment by krzema12** [comment]
What's interesting, this job works fine:
* in a PR: https://github.com/krzema12/github-actions-kotlin-dsl/runs/7646875999?check_suite_focus=true
* when pushing to main branch: https://github.com/krzema12/github-actions-kotlin-dsl/runs/7646953829?check_suite_focus=true

as if only the scheduled run was broken. Let's wait what happens with next scheduled run.

**Comment by jmfayard** [comment]
@krzema12 oh the file is `build/action-yaml/date.txt` 
maybe we need to do `File("build/action-yaml").mkdirs()` to be sure the parent directory exists

**Comment by krzema12** [comment]
Works again: https://github.com/krzema12/github-actions-kotlin-dsl/actions/runs/2802852587
